/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author dylan
 */
public class App extends javax.swing.JFrame {
    
    String Username;
    int Id;
    public App(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Music Training");
    }
    public App(String user,int id) {
        initComponents();
        Username=user;
        Id=id;
        welcome.setText("Bienvenido "+Username+"!");
        
        //Songs.setVisible(false);
         
        //Songs = new JList<>(Songs.getModel());
        this.setLocationRelativeTo(null);
        this.setTitle("Music Training");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchBG = new RoundedPanel(50,Color.GRAY);
        search1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Settings = new javax.swing.JButton();
        hear = new javax.swing.JLabel();
        Gym = new javax.swing.JButton();
        Yoga = new javax.swing.JButton();
        Run = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        MyPlayList = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Home = new javax.swing.JButton();
        searchBG1 = new RoundedPanel(50,Color.GRAY);
        search2 = new javax.swing.JLabel();
        searchBG2 = new RoundedPanel(50,Color.GRAY);
        search = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\main\\java\\images\\Logo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 130));

        searchBG.setBackground(new java.awt.Color(0, 0, 0));

        search1.setBackground(Color.gray);
        search1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search1.setText("Menu Principal");

        javax.swing.GroupLayout searchBGLayout = new javax.swing.GroupLayout(searchBG);
        searchBG.setLayout(searchBGLayout);
        searchBGLayout.setHorizontalGroup(
            searchBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBGLayout.createSequentialGroup()
                .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        searchBGLayout.setVerticalGroup(
            searchBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBGLayout.createSequentialGroup()
                .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(searchBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\main\\java\\images\\search.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 70, 60));

        Settings.setBackground(new java.awt.Color(0, 0, 0));
        Settings.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\main\\java\\images\\settings.png")); // NOI18N
        Settings.setBorder(null);
        Settings.setBorderPainted(false);
        Settings.setContentAreaFilled(false);
        Settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Settings.setFocusPainted(false);
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });
        jPanel1.add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 90, 80));

        hear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hear.setForeground(new java.awt.Color(255, 255, 255));
        hear.setText("Escucha estas Playlist creadas para ti!");
        jPanel1.add(hear, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 460, 50));

        Gym.setBackground(new java.awt.Color(102, 102, 102));
        Gym.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Gym.setForeground(new java.awt.Color(255, 255, 255));
        Gym.setText("Gym!");
        Gym.setBorderPainted(false);
        Gym.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gym.setFocusPainted(false);
        Gym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GymActionPerformed(evt);
            }
        });
        jPanel1.add(Gym, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, 100));

        Yoga.setBackground(new java.awt.Color(102, 102, 102));
        Yoga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Yoga.setForeground(new java.awt.Color(255, 255, 255));
        Yoga.setText("Yoga");
        Yoga.setBorderPainted(false);
        Yoga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Yoga.setFocusPainted(false);
        Yoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YogaActionPerformed(evt);
            }
        });
        jPanel1.add(Yoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 120, 100));

        Run.setBackground(new java.awt.Color(102, 102, 102));
        Run.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Run.setForeground(new java.awt.Color(255, 255, 255));
        Run.setText("Trotar");
        Run.setBorderPainted(false);
        Run.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Run.setFocusPainted(false);
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });
        jPanel1.add(Run, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 120, 100));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 640, 10));

        MyPlayList.setBackground(new java.awt.Color(0, 0, 0));
        MyPlayList.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\main\\java\\images\\MySongs.png")); // NOI18N
        MyPlayList.setBorder(null);
        MyPlayList.setBorderPainted(false);
        MyPlayList.setContentAreaFilled(false);
        MyPlayList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyPlayList.setFocusPainted(false);
        MyPlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyPlayListActionPerformed(evt);
            }
        });
        jPanel1.add(MyPlayList, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 110, 60));

        welcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 220, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 200, -1));

        Home.setBackground(new java.awt.Color(0, 0, 0));
        Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\main\\java\\images\\home.png")); // NOI18N
        Home.setBorder(null);
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 90, 60));

        searchBG1.setBackground(new java.awt.Color(0, 0, 0));

        search2.setBackground(Color.gray);
        search2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search2.setText("Mi Playlist");

        javax.swing.GroupLayout searchBG1Layout = new javax.swing.GroupLayout(searchBG1);
        searchBG1.setLayout(searchBG1Layout);
        searchBG1Layout.setHorizontalGroup(
            searchBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBG1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(search2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchBG1Layout.setVerticalGroup(
            searchBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBG1Layout.createSequentialGroup()
                .addComponent(search2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(searchBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 160, 40));

        searchBG2.setBackground(new java.awt.Color(0, 0, 0));

        search.setBackground(Color.gray);
        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("Busca tu cancion favorita!");

        javax.swing.GroupLayout searchBG2Layout = new javax.swing.GroupLayout(searchBG2);
        searchBG2.setLayout(searchBG2Layout);
        searchBG2Layout.setHorizontalGroup(
            searchBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBG2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchBG2Layout.setVerticalGroup(
            searchBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBG2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(searchBG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
        Settings settings=new Settings(this);
        settings.setVisible(true);
    }//GEN-LAST:event_SettingsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SearchSong SS=new SearchSong(Id);
        SS.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        hear.setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1FocusGained

    private void MyPlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyPlayListActionPerformed
        // TODO add your handling code here:
        MyLibrary me=new MyLibrary(Username);
        me.setVisible(true);
        
    }//GEN-LAST:event_MyPlayListActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        App app=new App();
        app.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_HomeActionPerformed

    private void GymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GymActionPerformed
        // TODO add your handling code here:
        PlayMusic music=new PlayMusic("Gym",Id);
        music.setVisible(true);
    }//GEN-LAST:event_GymActionPerformed

    private void YogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YogaActionPerformed
        // TODO add your handling code here:
        PlayMusic music=new PlayMusic("Yoga",Id);
        music.setVisible(true);
    }//GEN-LAST:event_YogaActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
        PlayMusic music=new PlayMusic("Run",Id);
        music.setVisible(true);
    }//GEN-LAST:event_RunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gym;
    private javax.swing.JButton Home;
    private javax.swing.JButton MyPlayList;
    private javax.swing.JButton Run;
    private javax.swing.JButton Settings;
    private javax.swing.JButton Yoga;
    private javax.swing.JLabel hear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel search;
    private javax.swing.JLabel search1;
    private javax.swing.JLabel search2;
    private javax.swing.JPanel searchBG;
    private javax.swing.JPanel searchBG1;
    private javax.swing.JPanel searchBG2;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
