/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Vista;

import com.mycompany.Controlador.Connect;
import com.mycompany.musictraining.Canciones;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dylan
 */
public class SearchSong extends javax.swing.JFrame {
    public Connection link;
    public Connect connect;
    int IdUser,IdSong;
    boolean Author=false;
    ArrayList<Integer>SongList=new ArrayList<Integer>();
    public SearchSong() {
        initComponents();
        add.setVisible(false);
        add.setEnabled(false);
        Listen.setVisible(false);
        Listen.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Search Song");
    }
    public SearchSong(int idUser) {
        initComponents();
        add.setVisible(false);
        add.setEnabled(false);
        Listen.setVisible(false);
        Listen.setEnabled(false);
        IdUser=idUser;
        this.setLocationRelativeTo(null);
        this.setTitle("Search Song");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(50,Color.GRAY);
        Text = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        ByAuthor = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Songs = new javax.swing.JList<>();
        add = new javax.swing.JToggleButton();
        Listen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\main\\java\\images\\Logo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 130));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        Text.setBackground(Color.gray);
        Text.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Text.setForeground(Color.DARK_GRAY);
        Text.setText("Busca tu cancion favorita!");
        Text.setBorder(null);
        Text.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Text.setSelectionColor(new java.awt.Color(0, 0, 0));
        Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 300, 40));

        Search.setBackground(new java.awt.Color(0, 0, 0));
        Search.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\main\\java\\images\\search.png")); // NOI18N
        Search.setBorderPainted(false);
        Search.setContentAreaFilled(false);
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.setFocusPainted(false);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 90, 60));

        ByAuthor.setBackground(new java.awt.Color(0, 0, 0));
        ByAuthor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ByAuthor.setForeground(new java.awt.Color(255, 255, 255));
        ByAuthor.setText("Buscar por autor");
        ByAuthor.setContentAreaFilled(false);
        ByAuthor.setFocusPainted(false);
        ByAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByAuthorActionPerformed(evt);
            }
        });
        jPanel1.add(ByAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, 30));

        Songs.setBackground(new java.awt.Color(0, 0, 0));
        Songs.setBorder(null);
        Songs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Songs.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(Songs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 260, 240));

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Añadir!");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 110, 50));

        Listen.setBackground(new java.awt.Color(0, 0, 0));
        Listen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Listen.setForeground(new java.awt.Color(255, 255, 255));
        Listen.setText("Escuchar!");
        Listen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Listen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListenActionPerformed(evt);
            }
        });
        jPanel1.add(Listen, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFocusGained
        // TODO add your handling code here:
        Text.setText("");
        Text.setForeground(Color.white);
    }//GEN-LAST:event_TextFocusGained

    private void TextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFocusLost
        // TODO add your handling code here:
        if(Text.getText().equals("")){
            Text.setText("Busca tu cancion favorita!");
            Text.setForeground(Color.darkGray);
        }
    }//GEN-LAST:event_TextFocusLost

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String query,name,author,addList;
        int id,count=0;
        connect=new Connect();
        link=connect.ConnectToDB();
        DefaultListModel model=new DefaultListModel();
        Songs.setModel(model);
        if(Author)
            query="select * from Song where Author= '"+Text.getText()+"'";
        else
            query="select * from Song where Name= '"+Text.getText()+"'";
        try{
            Statement s=link.createStatement();
            ResultSet rs=s.executeQuery(query);
            while(rs.next()){
                count++;
                id=rs.getInt("idSong");
                name=rs.getString("Name");
                author=rs.getString("Author");
                addList=author+"  -  "+name;
                SongList.add(id);
                model.addElement(addList);
            }
            if(count==0){
                JOptionPane.showMessageDialog(null, "No se encontro ninguna cancion o autor");
                Text.setText("");
                model.removeAllElements();
            }
            else{
                add.setVisible(true);
              add.setEnabled(true);
            }
            connect.CloseConection();
        }catch(SQLException e){
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, e);
            connect.CloseConection();
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void ByAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByAuthorActionPerformed
        // TODO add your handling code here:
        Author = ByAuthor.isSelected();
        
        
    }//GEN-LAST:event_ByAuthorActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Canciones song=new Canciones();
        if(song.AddSong(IdUser, SongList.get(Songs.getSelectedIndex()))){
            JOptionPane.showMessageDialog(null, "Cancion agregada!");
            Listen.setVisible(true);
            Listen.setEnabled(true);
        }
    }//GEN-LAST:event_addActionPerformed

    private void ListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListenActionPerformed
        // TODO add your handling code here:
        PlayMusic play=new PlayMusic(IdUser);
        play.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ListenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchSong().setVisible(true);
            }
        });
    }
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ByAuthor;
    private javax.swing.JButton Listen;
    private javax.swing.JButton Search;
    private javax.swing.JList<String> Songs;
    private javax.swing.JTextField Text;
    private javax.swing.JToggleButton add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
