/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Vista;

import com.mycompany.Controlador.Connect;
import com.mycompany.Controlador.Users;
import com.mycompany.musictraining.User;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
public class SignUp extends javax.swing.JFrame {

    public Connect connect;
    public Connection link;
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Welcome, Sign Up!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Mail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Listo = new javax.swing.JButton();
        User = new javax.swing.JTextField();
        ConfPass = new javax.swing.JPasswordField();
        Password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\test\\Images\\Logo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 150, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\test\\Images\\Music.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 150, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\dylan\\OneDrive\\Documentos\\NetBeansProjects\\MusicTraining\\src\\test\\Images\\Training.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 190, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo electronico");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrate!");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre de usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, 20));

        Mail.setBackground(new java.awt.Color(0, 0, 0));
        Mail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Mail.setForeground(new java.awt.Color(255, 255, 255));
        Mail.setBorder(null);
        jPanel1.add(Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 190, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 110, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirmar contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 20));

        Listo.setBackground(new java.awt.Color(0, 0, 0));
        Listo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Listo.setForeground(new java.awt.Color(255, 255, 255));
        Listo.setText("Listo!");
        Listo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoActionPerformed(evt);
            }
        });
        jPanel1.add(Listo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 100, 40));

        User.setBackground(new java.awt.Color(0, 0, 0));
        User.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setBorder(null);
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, 20));

        ConfPass.setBackground(new java.awt.Color(0, 0, 0));
        ConfPass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ConfPass.setForeground(new java.awt.Color(255, 255, 255));
        ConfPass.setBorder(null);
        jPanel1.add(ConfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 190, -1));

        Password.setBackground(new java.awt.Color(0, 0, 0));
        Password.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 190, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 190, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 190, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 190, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 190, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoActionPerformed
        Users user=new Users();
        boolean searchUser;
        connect=new Connect();
        link=connect.ConnectToDB();
        if(!User.getText().equals("")){
            searchUser=user.checkUserExists(link, User.getText());
            if(searchUser){
                JOptionPane.showMessageDialog(null, "Error: Elija Otro Nombre de Usuario");
                connect.CloseConection();
                User.setText("");
                Password.setText("");
                ConfPass.setText("");
                Mail.setText("");
            }
            else{
                if(Password.getText().equals(ConfPass.getText())){
                    User newUser=new User();
                    newUser.setUsername(User.getText());
                    newUser.setPassword(Password.getText());
                    newUser.setEmail(Mail.getText());
                    if(user.Create(newUser)){
                        JOptionPane.showMessageDialog(null, "Cuenta Creada Correctamente");
                        connect.CloseConection();
                        User.setText("");
                        Password.setText("");
                        ConfPass.setText("");
                        Mail.setText("");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error: No Se Pudo Crear Su Cuenta");
                        connect.CloseConection();
                        User.setText("");
                        Password.setText("");
                        ConfPass.setText("");
                        Mail.setText("");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error: Las Contraseñas No Coinciden");
                    connect.CloseConection();
                    Password.setText("");
                    ConfPass.setText("");
                }
            }
        }
    }//GEN-LAST:event_ListoActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfPass;
    private javax.swing.JButton Listo;
    private javax.swing.JTextField Mail;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables


}
